#If enabled, logs extra debugging information to the console. This information will appear in logs regardless of debug setting.
debug: false

#Name of your end world, usually to "world_the_end" on spigot
end: world_the_end

#Whether the egg teleporting causes the owner to no longer count as the owner of the egg
reset_owner: true
#Whether to tell players the new location of the egg (true) or the previous location of the egg (false) when it teleports
#!!! not yet implemented !!!
#accurate_loc: false

#Whether the egg should be invulnerable to damage
egg_inv: false
#Whether the egg should respawn after it is destroyed
resp_egg: true
#Whether the egg respawns immediately (true) or after a new dragon is spawned and killed (false) after the egg is destroyed
resp_imm: false
#Whether to drop any eggs that players have in their ender chest onto the ground.
#Setting this to false will prevent the player from removing that egg from their ender chest.
drop_enderchested_egg: false
#Whether the egg is allowed to be stored in bundles and shulker boxes
#WIP
#can_package_egg: true

#Whether to apply an entity tag to the egg owner (works like `/tag <playerName> add <tagName>`)
tag_owner: true
#The name of the tag to apply (selected like: `/tell @a[tag=<tagName>] <message>`)
#Do not overlap with tag names used by other plugins.
#If changing this while the egg is claimed, remove the old tag by running `/tag <playerName> remove <oldTagName>`.
owner_tag_name: eggOwner