#name of your end world, usually to "world_the_end" on spigot
end: world_the_end

#whether the egg teleporting resets the owner to none
reset_owner: true
#whether to give the new location of the egg (true) or the previous location of the egg (false) when it teleports
accurate_loc: false

#whether the egg should be invulnerable to damage
egg_inv: false
#whether the egg should respawn after it is destroyed
resp_egg: true
#whether the egg respawns immediately (true) or after a new dragon is spawned and killed (false) after the egg is destroyed
resp_imm: false
#whether to drop any eggs that players have in their ender chest onto the ground. Setting this to false will ignore that egg entirely.
drop_enderchested_egg: false
