name: EggHunt
main: egghunt.egghunt
version: 1.16.4

author: J0hnL0cke
commands:
    locateegg:
      description: Gives the current coordinates of the Dragon Egg
      usage: /<command>
      permission: <plugin name>.
      permission-message: You don't have <permission>
      
    trackegg:
      description: Sets a compass held in the player's hand to point to the Dragon Egg
      usage: /<command>
      permission: <plugin name>.
      permission-message: You don't have <permission>